# > condition: service_completed_successfully
# Require docker-compose version 1.29.2
# Run this command to download the current stable release of Docker Compose
# https://docs.docker.com/compose/install/

version: '3'

services:
  mods-downloader:
    build:
      context: ./mods-downloader
    image: minecraft-forge/mods-downloader
    volumes:
      - ./mods-downloader/mods.csv:/mods.csv
      - ./minecraft-server/server-contents/mods:/mods

  minecraft-server:
    depends_on:
      mods-downloader:
        condition: service_completed_successfully
    build:
      context: ./minecraft-server
    image: minecraft-forge/minecraft-server:1.12.2
    command: ${XMS_SIZE} ${XMX_SIZE}
    ports:
      - "${HOST_PORT}:25565"
    volumes:
      - ./minecraft-server/server-contents:/var/server-contents
